### ISSUE TITLE
playa honda

### ISSUE THREAD

**Issue by faso84** [palatinuse/monthly-report-issues#3]
MR doesn't see any airbnb commission

<img width="1061" alt="Schermata 2019-08-28 alle 18 12 34" src="https://user-images.githubusercontent.com/54636277/63873602-331db700-c9c0-11e9-8846-c52cb8563f22.png">

**Comment by palatinuse** [comment]
The reason for missing airbnb commissions: this is a new apartment, where the app does not yet know, if GROSS or NET is the calculation method.
This information will be editable in the database app.
Furthermore, I will show a warning for apartments, where some fees are missing.

**Comment by palatinuse** [comment]
Here is the complete list of apartments that are affected:

      id                                             name
1  49965 Apartment in the centre of Playa De Las Americas
2  49958                  HEATED POOL 300M FROM THE BEACH
3  49960                  Letizia Bungalow with pool view
4  53201               Design Apartment near Duomo square
5  53865         Studio with sea view 300m from the beach
6  54352   Beach front apartment in Playa de Las Americas
7  54448          Panoramic apartment 300m from the beach
8  55359                  Nice apartment with heated pool
9  57343              Nice apartment near the city center
10 60824  CIARDI · Design Apartment near San Siro Stadium
11 60303            Sweet 2 bedrooms home in Milan center
12 61713  TRASERA 28 A  · Modern flat near Playa San Blas
13 62735                GOVONE · 2 bedrooms flat in Milan
14 64872           SAN NICOLAO · Modern central apartment
15 65353                   Nice flat near the city center
16 65756  GESU' · 5 bedrooms apartment in the city center

**Comment by palatinuse** [comment]
I will look fill in the missing information now...

**Comment by faso84** [comment]
ok thanks, can you write me where it will done please?

**Comment by palatinuse** [comment]
Even worse: all 4 airbnb reservations on playa honda were missing the airbnb commission in HW. Thus, my method for filling in the missing values failed for these 4 entries...

**Comment by palatinuse** [comment]
There is a systematic failure in HW and/or airbnb here for this apartment. It has 20 AirBnB reservations, and the commission is missing for all of them. 
Thus, I cannot calculate from the data, if the calculation is based on NET or GROSS. However, as it is Spain, I will just assume NET.

**Comment by palatinuse** [comment]
I have reverse-engineered NET or GROSS for 12 out of 16 apartments. The following 4 apartments are still unclear, as I do not have any AirBnB reservations for them???


id<int> | name<chr> |   |   |  
-- | -- | -- | -- | --
60824 | CIARDI · Design Apartment near San Siro Stadium |   |   |  
61713 | TRASERA 28 A · Modern flat near Playa San Blas |   |   |  
65353 | Nice flat near the city center |   |   |  
65756 | GESU' · 5 bedrooms apartment in the city center
