### ISSUE TITLE
monte nero

### ISSUE THREAD

**Issue by faso84** [palatinuse/monthly-report-issues#7]
all the pointed values are zero

<img width="1014" alt="Schermata 2019-08-28 alle 19 26 59" src="https://user-images.githubusercontent.com/54636277/63878940-e12e5e80-c9ca-11e9-9bdc-d901abb0a404.png">

**Comment by palatinuse** [comment]
I have updated the policy to "flexible" in row 10.
However, even with "flexible" in row 17, there would be "only cleaning fee refunded" according to the rules.

<img width="1427" alt="Screenshot 2019-08-29 at 00 17 48" src="https://user-images.githubusercontent.com/5019897/63896601-c40d8600-c9f2-11e9-9df8-8b178377a644.png">

**Comment by palatinuse** [comment]
So for row 17: do you see a full refund on the invoice from Booking.com? If yes, I will hard-code this manual correction.

**Comment by faso84** [comment]
yes please we need an hard-code fix for the row 17. thanks

**Comment by palatinuse** [comment]
DONE.
